# Generated by Django 4.1 on 2022-08-11 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mycontacts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='sumary',
            new_name='summary',
        ),
    ]
