# Generated by Django 4.1 on 2022-08-15 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycontacts', '0002_rename_sumary_contact_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
